# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# Enable OTA
ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret fallback_password

captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    entity_category: diagnostic
    disabled_by_default: true
    update_interval: 60s
